In [2]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
from numpy import *
x = linspace(0,2*pi,1000)
x

array([0.        , 0.00628947, 0.01257895, 0.01886842, 0.0251579 ,
       0.03144737, 0.03773685, 0.04402632, 0.0503158 , 0.05660527,
       0.06289475, 0.06918422, 0.0754737 , 0.08176317, 0.08805265,
       0.09434212, 0.1006316 , 0.10692107, 0.11321055, 0.11950002,
       0.1257895 , 0.13207897, 0.13836845, 0.14465792, 0.15094739,
       0.15723687, 0.16352634, 0.16981582, 0.17610529, 0.18239477,
       0.18868424, 0.19497372, 0.20126319, 0.20755267, 0.21384214,
       0.22013162, 0.22642109, 0.23271057, 0.23900004, 0.24528952,
       0.25157899, 0.25786847, 0.26415794, 0.27044742, 0.27673689,
       0.28302637, 0.28931584, 0.29560531, 0.30189479, 0.30818426,
       0.31447374, 0.32076321, 0.32705269, 0.33334216, 0.33963164,
       0.34592111, 0.35221059, 0.35850006, 0.36478954, 0.37107901,
       0.37736849, 0.38365796, 0.38994744, 0.39623691, 0.40252639,
       0.40881586, 0.41510534, 0.42139481, 0.42768429, 0.43397376,
       0.44026323, 0.44655271, 0.45284218, 0.45913166, 0.46542

In [6]:
y = sin(x)
y

array([ 0.00000000e+00,  6.28943332e-03,  1.25786178e-02,  1.88673048e-02,
        2.51552454e-02,  3.14421909e-02,  3.77278927e-02,  4.40121020e-02,
        5.02945704e-02,  5.65750492e-02,  6.28532900e-02,  6.91290446e-02,
        7.54020646e-02,  8.16721019e-02,  8.79389084e-02,  9.42022363e-02,
        1.00461838e-01,  1.06717465e-01,  1.12968871e-01,  1.19215809e-01,
        1.25458030e-01,  1.31695289e-01,  1.37927338e-01,  1.44153931e-01,
        1.50374822e-01,  1.56589764e-01,  1.62798512e-01,  1.69000820e-01,
        1.75196443e-01,  1.81385136e-01,  1.87566653e-01,  1.93740751e-01,
        1.99907185e-01,  2.06065711e-01,  2.12216086e-01,  2.18358066e-01,
        2.24491409e-01,  2.30615871e-01,  2.36731210e-01,  2.42837185e-01,
        2.48933554e-01,  2.55020076e-01,  2.61096510e-01,  2.67162616e-01,
        2.73218154e-01,  2.79262883e-01,  2.85296566e-01,  2.91318963e-01,
        2.97329837e-01,  3.03328948e-01,  3.09316061e-01,  3.15290939e-01,
        3.21253344e-01,  